### ISSUE TITLE
Unifi udm pro intergration

### ISSUE THREAD

**Issue by RubenDijk** [troinine/hass-config#1]
Hello Troinine,

I like your work! I saw that you are using a script to read data from the unifi udm pro. Could you explain to me how you did this? I took the python code and implemented it the same way. I just can't get it to work yet 

Logger: homeassistant.components.command_line
Source: components/command_line/__init__.py:48
Integration: command_line (documentation, issues)
First occurred: January 23, 2023 at 15:57:57 (121 occurrences)
Last logged: 21:57:58

Command failed (with return code 1): python3 /config/scripts/unifi_info.py

**Comment by troinine** [comment]
Hi @RubenDijk and nice to see that you find my repo useful!

Note that I have tested this only with Unifi Dream Machine, not with UDM Pro.

My approach was to create a new user in the Unifi Admin UI that only has role `Viewer` with local access. Security first! Then configure this user's credentials and the UDM host (either domain name or IP) in your `secrets.yaml` e.g.

```yaml
udm_host: my-udm.local # or ip
udm_username: <the username of the user you created in Unifi Admin UI>
udm_password: <the password of the user you created in Unifi Admin UI>
```

I would suggest you first test the script in your home assistant server. If you use docker like I do, you jump into the container and run the python script:

```bash
$ docker exec -it home-assistant bash

$ python3 /config/scripts/unifi_info.py
```

You should see something like this
```json
{"cpu": "15.2", "cpu_temp": 76.2, "system_temp": 63.0, "memory": "82.8", "disk": 14.1, "internet": true, "uptime": "2023-01-19T17:10:10", "availability": 100.0, "average_latency": 1, "down": 0.003984, "up": 0.005088, "version": "1.12.33"}
```
or an error if something is not correct.

Hope this helps!
