### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by pex81** [troinine/hass-config#3]
Hi, I'm trying your dashboard, very nice, I had used hass-config in the past and I was happy with it.
I wanted to understand something, how do you generate binary_sensor.* for notifications and how do you increase the sensor.notification_count counter?
Thanks, and merry Christmas.

**Comment by RubenDijk** [comment]
> Hi, I'm trying your dashboard, very nice, I had used hass-config in the past and I was happy with it. I wanted to understand something, how do you generate binary_sensor.* for notifications and how do you increase the sensor.notification_count counter? Thanks, and merry Christmas.

This is the counter.
```
    - name: notification_count
      unique_id: notification_count
      state: |
        {{ states.binary_sensor | selectattr('state', 'equalto', 'on') | rejectattr('attributes.priority', 'equalto', 'info') | map(attribute='entity_id') | select('search', 'notification') | list | length }}
```

Here is a example of a notify: (template binary_sensor)

```
    - name: notification_replace_airco_filters
      unique_id: notification_replace_airco_filters
      icon: mdi:air-filter
      state: "{{ iif(states('sensor.airco_filters_days_remaining') | int(1) <= 0, 'on', 'off')}}"
      attributes:
        icon_color: var(--warning-color)
        text_summary: "De filters van de airco vervangen"
        text_description: "Filters voor het laatst vervangen {{states('input_datetime.airco_filters_replaced') }}"
```

Template sensor:

```
    - name: airco_filters_days_remaining
      unique_id: airco_filters_days_remaining
      state: |
        {% set diff_days = (30 * 4) - (((as_timestamp(now()) - as_timestamp(states('input_datetime.airco_filters_replaced'), 0)) / 60 / 60 / 24) | int) %}
        {{ [diff_days, 0] | max }}
      attributes:
        icon: mdi:clock
        friendly_name: Filters vervangen
        unit_of_measurement: Dagen
```

i hope this helps you.
